import { Geist, Geist_Mono, DynaPuff } from "next/font/google";
import "./globals.css";
import { BackgroundOrnaments } from "../components/BackgroundOrnaments";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dynaPuff = DynaPuff({
  variable: "--font-dynapuff",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

function LayoutWrapper({ children }) {
  // Simple shell to provide consistent background and full-height layout
  return <div className="min-h-screen bg-white">{children}</div>;
}

export const metadata = {
  title: "Literakids",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${dynaPuff.variable} antialiased`}>
        <LayoutWrapper>
          <BackgroundOrnaments />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
